-- FUNCTIONS 

DELIMITER //

CREATE FUNCTION sqare_it(x INT) -- SPECIFY A VARIABLE AND INPUT DATA TYPE
RETURNS INT -- OUTPUT DATA TYPE
DETERMINISTIC -- REFER MYSQL DOCS FOR FUNCTIONS 
BEGIN
	return x*x;
END //

DELIMITER ;

SELECT
	unit_price,
    sqare_it(unit_price)
FROM
	dim_product;